#!/usr/bin/perl

# Conversion script to change old-style regression files to new-style

# Global variables
%diag      = ();
$diag_name = $ARGV[0];

&read_in_files;
&create_new_files( $diag_name );

sub get_cfg {

  opendir( CDIR, "../regress" );

  while( $file = readdir( CDIR ) ) {
    chomp( $file );
    if( $file =~ /(.*)\.cfg$/ ) {
      $diag{$1} |= 0x1;
    }
  }

  closedir( CDIR );

}

sub get_verilog {

  opendir( VDIR, "../verilog" );

  while( $file = readdir( VDIR ) ) {
    chomp( $file );
    if( $file =~ /(.*)\.v$/ ) {
      $diag{$1} |= 0x2;
    }
  }

  closedir( VDIR );

}

sub get_cdd {

  my $cdd_name;

  opendir( CDIR, "../cdd" );

  while( $file = readdir( CDIR ) ) {
    chomp( $file );
    if( $file =~ /(.*)\.cdd$/ ) {
      $diag{$1} |= 0x4;
    }
  }

  closedir( CDIR );

}

sub get_report {

  my $rpt_name, $rpt_type;

  opendir( RDIR, "../rpt" );

  while( $file = readdir( RDIR ) ) {
    chomp( $file );
    if( $file =~ /(.*).rpt(.*)$/ ) {
      $rpt_name = $1;
      $rpt_type = $2;
      if( $rpt_type eq "M" ) {
        $diag{$rpt_name} |= 0x8;
      } elsif( $rpt_type eq "WM" ) {
        $diag{$rpt_name} |= 0x10;
      } elsif( $rpt_type eq "I" ) {
        $diag{$rpt_name} |= 0x20;
      } elsif( $rpt_type eq "WI" ) {
        $diag{$rpt_name} |= 0x40;
      } else {
        die "Unknown report type ${rpt_type}: $!\n";
      }
    }
  }

  closedir( RDIR );

}

sub get_error {

  opendir( EDIR, "../err" );

  while( $file = readdir( EDIR ) ) {
    chomp( $file );
    if( $file =~ /(.*).err$/ ) {
      $diag{$1} |= 0x80;
    }
  }

  closedir( EDIR );

}

sub read_in_files {

  &get_cfg;
  &get_verilog;
  &get_cdd;
  &get_report;
  &get_error;

}

sub create_new_files {

  my $d = $_[0];
  my @diags_to_convert = ();

  if( $d eq "" ) {
    @diags_to_convert = keys( %diag );
  } else {
    $diags_to_convert[@diags_to_convert] = $d;
  }

  foreach $d (@diags_to_convert) {

    if( ($diag{$d} & 0xfd) != 0 ) {

      print "Converting ${d}...\n";

      open( DIAG, ">${d}.v" );

      if( ($diag{$d} & 0x2) != 0 ) {
        $tmp = `cat ../verilog/${d}.v`;
        print DIAG "$tmp";
      }

      print DIAG "\n";
      print DIAG "/* HEADER\n";
      print DIAG "GROUPS ${d} iv vcs vcd lxt all\n";
      print DIAG "SIM    ${d} all iv vcd  : iverilog ${d}.v; ./a.out                             : ${d}.vcd\n";
      print DIAG "SIM    ${d} all iv lxt  : iverilog ${d}.v; ./a.out -lxt2; mv ${d}.vcd ${d}.lxt : ${d}.lxt\n";
      print DIAG "SIM    ${d} all vcs vcd : vcs ${d}.v; ./simv                                   : ${d}.vcd\n";
      if( ($diag{$d} & 0x1) != 0 ) {
        $tmp = `cat ../regress/${d}.cfg`;
        chomp( $tmp );
        if( ($diag{$d} & 0x80) != 0 ) {
          $tmp .= " > ${d}.err";
        }
        print DIAG "SCORE  ${d}.vcd     : ${tmp} : ${d}.cdd\n";
        $tmp =~ s/vcd/lxt/g;
        print DIAG "SCORE  ${d}.lxt     : ${tmp} : ${d}.cdd\n";
      }
      if( ($diag{$d} & 0x8) != 0 ) {
        print DIAG "REPORT ${d}.cdd 1   : -d v -o ${d}.rptM ${d}.cdd                         : ${d}.rptM\n";
      }
      if( ($diag{$d} & 0x10) != 0 ) {
        print DIAG "REPORT ${d}.cdd 2   : -d v -w -o ${d}.rptWM ${d}.cdd                     : ${d}.rptWM\n";
      }
      if( ($diag{$d} & 0x20) != 0 ) {
        print DIAG "REPORT ${d}.cdd 3   : -d v -i -o ${d}.rptI ${d}.cdd                      : ${d}.rptI\n";
      }
      if( ($diag{$d} & 0x40) != 0 ) {
        print DIAG "REPORT ${d}.cdd 4   : -d v -w -i -o ${d}.rptWI ${d}.cdd                  : ${d}.rptWI\n";
      }
      print DIAG "*/\n";

      # Generate error output
      if( ($diag{$d} & 0x80) != 0 ) {
        $tmp = `cat ../err/${d}.err`;
        print DIAG "\n/* OUTPUT ${d}.err\n";
        print DIAG "$tmp";
        print DIAG "*/\n";
      }

      # Generate CDD output
      if( ($diag{$d} & 0x4) != 0 ) {
        $tmp = `cat ../cdd/${d}.cdd`;
        print DIAG "\n/* OUTPUT ${d}.cdd\n";
        print DIAG "$tmp";
        print DIAG "*/\n";
      }

      # Generate report output
      if( ($diag{$d} & 0x8) != 0 ) {
        $tmp = `cat ../rpt/${d}.rptM`;
        print DIAG "\n/* OUTPUT ${d}.rptM\n";
        print DIAG "$tmp";
        print DIAG "*/\n";
      }
      if( ($diag{$d} & 0x10) != 0 ) {
        $tmp = `cat ../rpt/${d}.rptWM`;
        print DIAG "\n/* OUTPUT ${d}.rptWM\n";
        print DIAG "$tmp";
        print DIAG "*/\n";
      }
      if( ($diag{$d} & 0x20) != 0 ) {
        $tmp = `cat ../rpt/${d}.rptI`;
        print DIAG "\n/* OUTPUT ${d}.rptI\n";
        print DIAG "$tmp";
        print DIAG "*/\n";
      }
      if( ($diag{$d} & 0x40) != 0 ) {
        $tmp = `cat ../rpt/${d}.rptWI`;
        print DIAG "\n/* OUTPUT ${d}.rptWI\n";
        print DIAG "$tmp";
        print DIAG "*/\n";
      }

      close( DIAG );

      die;

    } 

  }

}
