#ifndef __GENPROF_H__
#define __GENPROF_H__

/*
 Copyright (c) 2006 Trevor Williams

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by the Free Software
 Foundation; either version 2 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 See the GNU General Public License for more details.

 You should have received a copy of the GNU General Public License along with this program;
 if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

/*!
 \file    genprof.h
 \author  Trevor Williams  (phase1geo@gmail.com)
 \date    12/10/2007
*/

#include "defines.h"

#define NUM_PROFILES 223

#ifdef DEBUG
#define UNREGISTERED 0
#define ARC_GET_ENTRY_WIDTH 1
#define ARC_SET_WIDTH 2
#define ARC_GET_WIDTH 3
#define ARC_SET_MAX_SIZE 4
#define ARC_GET_MAX_SIZE 5
#define ARC_SET_CURR_SIZE 6
#define ARC_GET_CURR_SIZE 7
#define ARC_SET_SUPPL 8
#define ARC_GET_SUPPL 9
#define ARC_SET_STATES 10
#define ARC_SET_ENTRY_SUPPL 11
#define ARC_GET_ENTRY_SUPPL 12
#define ARC_FIND 13
#define ARC_CREATE 14
#define ARC_ADD 15
#define ARC_COMPARE_STATES 16
#define ARC_COMPARE_ALL_STATES 17
#define ARC_STATE_TOTAL 18
#define ARC_STATE_HITS 19
#define ARC_TRANSITION_TOTAL 20
#define ARC_TRANSITION_HITS 21
#define ARC_GET_STATS 22
#define ARC_DB_WRITE 23
#define ARC_READ_GET_NEXT_VALUE 24
#define ARC_DB_READ 25
#define ARC_STATE_TO_STRING 26
#define ARC_DB_MERGE 27
#define ARC_GET_STATES 28
#define ARC_GET_TRANSITIONS 29
#define ARC_ARE_ANY_EXCLUDED 30
#define ARC_DEALLOC 31
#define ASSERTION_PARSE 32
#define ASSERTION_PARSE_ATTR 33
#define ASSERTION_GET_STATS 34
#define ASSERTION_DISPLAY_INSTANCE_SUMMARY 35
#define ASSERTION_INSTANCE_SUMMARY 36
#define ASSERTION_DISPLAY_FUNIT_SUMMARY 37
#define ASSERTION_FUNIT_SUMMARY 38
#define ASSERTION_DISPLAY_VERBOSE 39
#define ASSERTION_INSTANCE_VERBOSE 40
#define ASSERTION_FUNIT_VERBOSE 41
#define ASSERTION_REPORT 42
#define ASSERTION_GET_FUNIT_SUMMARY 43
#define ASSERTION_COLLECT 44
#define ASSERTION_GET_COVERAGE 45
#define ATTRIBUTE_CREATE 46
#define ATTRIBUTE_PARSE 47
#define ATTRIBUTE_DEALLOC 48
#define BIND_ADD 49
#define BIND_APPEND_FSM_EXPR 50
#define BIND_REMOVE 51
#define BIND_FIND_SIG_NAME 52
#define BIND_PARAM 53
#define BIND_SIGNAL 54
#define BIND_TASK_FUNCTION_PORTS 55
#define BIND_TASK_FUNCTION_NAMEDBLOCK 56
#define BIND_PERFORM 57
#define BIND_DEALLOC 58
#define CODEGEN_CREATE_EXPR_HELPER 59
#define CODEGEN_CREATE_EXPR 60
#define CODEGEN_GEN_EXPR 61
#define DB_CLOSE 62
#define DB_CHECK_FOR_TOP_MODULE 63
#define DB_WRITE 64
#define DB_READ 65
#define DB_SCALE_TO_PRECISION 66
#define DB_CREATE_UNNAMED_SCOPE 67
#define DB_IS_UNNAMED_SCOPE 68
#define DB_SET_TIMESCALE 69
#define DB_GET_CURR_FUNIT 70
#define DB_ADD_INSTANCE 71
#define DB_ADD_MODULE 72
#define DB_END_MODULE 73
#define DB_ADD_FUNCTION_TASK_NAMEDBLOCK 74
#define DB_END_FUNCTION_TASK_NAMEDBLOCK 75
#define DB_ADD_DECLARED_PARAM 76
#define DB_ADD_OVERRIDE_PARAM 77
#define DB_ADD_VECTOR_PARAM 78
#define DB_ADD_DEFPARAM 79
#define DB_ADD_SIGNAL 80
#define DB_ADD_ENUM 81
#define DB_END_ENUM_LIST 82
#define DB_ADD_TYPEDEF 83
#define DB_FIND_SIGNAL 84
#define DB_ADD_GEN_ITEM_BLOCK 85
#define DB_FIND_GEN_ITEM 86
#define DB_FIND_TYPEDEF 87
#define DB_GET_CURR_GEN_BLOCK 88
#define DB_CURR_SIGNAL_COUNT 89
#define DB_CREATE_EXPRESSION 90
#define DB_BIND_EXPR_TREE 91
#define DB_CREATE_EXPR_FROM_STATIC 92
#define DB_ADD_EXPRESSION 93
#define DB_CREATE_SENSITIVITY_LIST 94
#define DB_PARALLELIZE_STATEMENT 95
#define DB_CREATE_STATEMENT 96
#define DB_ADD_STATEMENT 97
#define DB_REMOVE_STATEMENT_FROM_CURRENT_FUNIT 98
#define DB_REMOVE_STATEMENT 99
#define DB_CONNECT_STATEMENT_TRUE 100
#define DB_CONNECT_STATEMENT_FALSE 101
#define DB_GEN_ITEM_CONNECT_TRUE 102
#define DB_GEN_ITEM_CONNECT_FALSE 103
#define DB_GEN_ITEM_CONNECT 104
#define DB_STATEMENT_CONNECT 105
#define DB_CREATE_ATTR_PARAM 106
#define DB_PARSE_ATTRIBUTE 107
#define DB_REMOVE_STMT_BLKS_CALLING_STATEMENT 108
#define DB_GEN_CURR_INST_SCOPE 109
#define DB_SYNC_CURR_INSTANCE 110
#define DB_SET_VCD_SCOPE 111
#define DB_VCD_UPSCOPE 112
#define DB_ASSIGN_SYMBOL 113
#define DB_SET_SYMBOL_CHAR 114
#define DB_SET_SYMBOL_STRING 115
#define DB_DO_TIMESTEP 116
#define COMBINATION_CALC_DEPTH 117
#define COMBINATION_DOES_MULTI_EXP_NEED_UL 118
#define COMBINATION_MULTI_EXPR_CALC 119
#define COMBINATION_IS_EXPR_MULTI_NODE 120
#define COMBINATION_GET_TREE_STATS 121
#define COMBINATION_RESET_COUNTED_EXPRS 122
#define COMBINATION_RESET_COUNTED_EXPR_TREE 123
#define COMBINATION_GET_STATS 124
#define COMBINATION_GET_FUNIT_SUMMARY 125
#define COMBINATION_DISPLAY_INSTANCE_SUMMARY 126
#define COMBINATION_INSTANCE_SUMMARY 127
#define COMBINATION_DISPLAY_FUNIT_SUMMARY 128
#define COMBINATION_FUNIT_SUMMARY 129
#define COMBINATION_DRAW_LINE 130
#define COMBINATION_DRAW_CENTERED_LINE 131
#define COMBINATION_UNDERLINE_TREE 132
#define COMBINATION_PREP_LINE 133
#define COMBINATION_UNDERLINE 134
#define COMBINATION_UNARY 135
#define COMBINATION_EVENT 136
#define COMBINATION_TWO_VARS 137
#define COMBINATION_MULTI_VAR_EXPRS 138
#define COMBINATION_MULTI_EXPR_OUTPUT_LENGTH 139
#define COMBINATION_MULTI_EXPR_OUTPUT 140
#define COMBINATION_MULTI_VARS 141
#define COMBINATION_GET_MISSED_EXPR 142
#define COMBINATION_LIST_MISSED 143
#define COMBINATION_OUTPUT_EXPR 144
#define COMBINATION_DISPLAY_VERBOSE 145
#define COMBINATION_INSTANCE_VERBOSE 146
#define COMBINATION_FUNIT_VERBOSE 147
#define COMBINATION_COLLECT 148
#define COMBINATION_GET_EXCLUDE_LIST 149
#define COMBINATION_GET_EXPRESSION 150
#define COMBINATION_GET_COVERAGE 151
#define COMBINATION_REPORT 152
#define LEXER_CSTRING_A 153
#define LEXER_KEYWORD_A 154
#define LEXER_ESCAPED_NAME 155
#define LEXER_SYSTEM_CALL 156
#define PROCESS_TIMESCALE 157
#define RESET_LEXER 158
#define ENUMERATE_ADD_ITEM 159
#define ENUMERATE_END_LIST 160
#define ENUMERATE_RESOLVE 161
#define ENUMERATE_DEALLOC 162
#define ENUMERATE_DEALLOC_LIST 163
#define EXPRESSION_CREATE_VALUE 164
#define EXPRESSION_CREATE 165
#define EXPRESSION_SET_VALUE 166
#define EXPRESSION_SET_SIGNED 167
#define EXPRESSION_RESIZE 168
#define EXPRESSION_GET_ID 169
#define EXPRESSION_GET_FIRST_LINE_EXPR 170
#define EXPRESSION_GET_LAST_LINE_EXPR 171
#define EXPRESSION_GET_CURR_DIMENSION 172
#define EXPRESSION_FIND_RHS_SIGS 173
#define EXPRESSION_FIND_PARAMS 174
#define EXPRESSION_FIND_ULINE_ID 175
#define EXPRESSION_FIND_EXPR 176
#define EXPRESSION_CONTAINS_EXPR_CALLING_STMT 177
#define EXPRESSION_GET_ROOT_STATEMENT 178
#define EXPRESSION_ASSIGN_EXPR_IDS 179
#define EXPRESSION_DB_WRITE 180
#define EXPRESSION_DB_WRITE_TREE 181
#define EXPRESSION_DB_READ 182
#define EXPRESSION_DB_MERGE 183
#define EXPRESSION_STRING_OP 184
#define EXPRESSION_STRING 185
#define EXPRESSION_DISPLAY 186
#define EXPRESSION_OP_FUNC__XOR 187
#define EXPRESSION_OP_FUNC__MULTIPLY 188
#define EXPRESSION_OP_FUNC__DIVIDE 189
#define EXPRESSION_OP_FUNC__MOD 190
#define EXPRESSION_OP_FUNC__ADD 191
#define EXPRESSION_OP_FUNC__SUBTRACT 192
#define EXPRESSION_OP_FUNC__AND 193
#define EXPRESSION_DEALLOC 194
#define PARSER_PORT_DECLARATION_A 195
#define PARSER_PORT_DECLARATION_B 196
#define PARSER_PORT_DECLARATION_C 197
#define PARSER_STATIC_EXPR_PRIMARY_A 198
#define PARSER_STATIC_EXPR_PRIMARY_B 199
#define PARSER_EXPRESSION_LIST_A 200
#define PARSER_EXPRESSION_LIST_B 201
#define PARSER_EXPRESSION_LIST_C 202
#define PARSER_EXPRESSION_LIST_D 203
#define PARSER_IDENTIFIER_A 204
#define PARSER_GENERATE_CASE_ITEM_A 205
#define PARSER_GENERATE_CASE_ITEM_B 206
#define PARSER_GENERATE_CASE_ITEM_C 207
#define PARSER_STATEMENT_BEGIN_A 208
#define PARSER_STATEMENT_FORK_A 209
#define PARSER_STATEMENT_FOR_A 210
#define PARSER_CASE_ITEM_A 211
#define PARSER_CASE_ITEM_B 212
#define PARSER_CASE_ITEM_C 213
#define PARSER_DELAY_VALUE_A 214
#define PARSER_DELAY_VALUE_B 215
#define PARSER_PARAMETER_VALUE_BYNAME_A 216
#define PARSER_GATE_INSTANCE_A 217
#define PARSER_GATE_INSTANCE_B 218
#define PARSER_GATE_INSTANCE_C 219
#define PARSER_GATE_INSTANCE_D 220
#define PARSER_LIST_OF_NAMES_A 221
#define PARSER_LIST_OF_NAMES_B 222

extern profiler profiles[NUM_PROFILES];
#endif

extern unsigned int profile_index;

#endif

