#!/usr/bin/perl

# Name:     cdd_diff
# Author:   Trevor Williams  (trevorw<charter.net>)
# Date:     11/21/2006
# Usage:    cdd_diff <CDD> <CDD>

$cdd1 = $ARGV[0];
$cdd2 = $ARGV[1];

if( ($cdd1 eq "") || ($cdd2 eq "") ) {
  die "Usage:  cdd_diff <CDD> <CDD>\n";
}

$line_cnt = 1;
$retval   = 0;

open( CDD1, "$cdd1" ) || die "Can't open $cdd1: $!\n";
open( CDD2, "$cdd2" ) || die "Can't open $cdd1: $!\n";

while( ($l1 = <CDD1>) && ($l2 = <CDD2>) ) {

  chomp( $l1 );
  chomp( $l2 );

  @line1 = split( /\s+/, $l1 );
  @line2 = split( /\s+/, $l2 );

  # Skip score argument line
  if( ($line1[0] ne "8") || ($line2[0] ne "8") ) {
    if( ($line1[0] eq "2") && ($line2[0] eq "2") ) {
      if( ($line1[4] ne "0") && ($line2[4] ne "0") ) {
        $line1[4] = "0";
        $line2[4] = "0";
      }
    }
    if( "@line1" ne "@line2" ) {
      print "-${line_cnt}-------\n";
      print "< @line1\n";
      print "> @line2\n";
      $retval = 1;
    }
  }

  $line_cnt++;

}

close( CDD1 );
close( CDD2 );

exit $retval;
