#!/usr/bin/perl

# Name:     cdd_diff
# Author:   Trevor Williams  (phase1geo<gmail.com>)
# Date:     11/21/2006
# Usage:    cdd_diff <CDD> <CDD>

$cdd1 = $ARGV[0];
$cdd2 = $ARGV[1];

if( ($cdd1 eq "") || ($cdd2 eq "") ) {
  die "Usage:  cdd_diff <CDD> <CDD>\n";
}

$retval   = 0;

open( CDD1, "$cdd1" ) || die "Can't open $cdd1: $!\n";
open( CDD2, "$cdd2" ) || die "Can't open $cdd1: $!\n";
open( OCDD1, ">$cdd1.tmpdiff" ) || die "Can't open $cdd1.tmpdiff: $!\n";
open( OCDD2, ">$cdd2.tmpdiff" ) || die "Can't open $cdd2.tmpdiff: $!\n";

while( ($l1 = <CDD1>) && ($l2 = <CDD2>) ) {

  chomp( $l1 );
  chomp( $l2 );

  @line1 = split( /\s+/, $l1 );
  @line2 = split( /\s+/, $l2 );

  # Skip score argument line
  if( ($line1[0] ne "8") || ($line2[0] ne "8") ) {
    if( ($line1[0] eq "2") && ($line2[0] eq "2") ) {
      if( ($line1[4] ne "0") && ($line2[4] ne "0") ) {
        $line1[4] = "0";
        $line2[4] = "0";
      }
    }
    print OCDD1 "@line1\n";
    print OCDD2 "@line2\n";
  }

}

close( CDD1 );
close( CDD2 );
close( OCDD1 );
close( OCDD2 );

$retval = system( "diff $cdd1.tmpdiff $cdd2.tmpdiff" ) / 256;
system( "rm -f $cdd1.tmpdiff $cdd2.tmpdiff" ) && die;

exit $retval;
